
[env]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
build_flags = -DBOARD_HAS_PSRAM
lib_deps = dvarrel/ESPping

[env:node_a]
build_flags = ${env.build_flags} -DNODE_ID=\"node_a\" -DNODE_LOCATION=\"living_room\"

[env:node_b]
build_flags = ${env.build_flags} -DNODE_ID=\"node_b\" -DNODE_LOCATION=\"basement\"
