
[env]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -Iinclude
lib_deps =
    dvarrel/ESPping
    knolleary/PubSubClient@^2.8 ; The standard, lightweight MQTT client library for Arduino/ESP32 — it handles the actual protocol details (connecting to a broker, publishing messages, maintaining the connection) so you're not implementing MQTT from scratch.

[env:node_a]
build_flags = ${env.build_flags} -DNODE_ID=\"node_a\" -DNODE_LOCATION=\"living_room\"

[env:node_b]
build_flags = ${env.build_flags} -DNODE_ID=\"node_b\" -DNODE_LOCATION=\"basement\"
